In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model
from sklearn.model_selection import train_test_split
data = pd.read_csv('diabetes.csv')
data.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [2]:
Response_PredVars = data[['Pregnancies','Glucose','BloodPressure',
                          'SkinThickness','Insulin','BMI','DiabetesPedigreeFunction',
                          'Age','Outcome']]
Response_PredVars.corr()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
Pregnancies,1.000000,0.129459,0.141282,-0.081672,-0.073535,0.017683,-0.033523,0.544341,0.221898
Glucose,0.129459,1.000000,0.152590,0.057328,0.331357,0.221071,0.137337,0.263514,0.466581
BloodPressure,0.141282,0.152590,1.000000,0.207371,0.088933,0.281805,0.041265,0.239528,0.065068
SkinThickness,-0.081672,0.057328,0.207371,1.000000,0.436783,0.392573,0.183928,-0.113970,0.074752
Insulin,-0.073535,0.331357,0.088933,0.436783,1.000000,0.197859,0.185071,-0.042163,0.130548
BMI,0.017683,0.221071,0.281805,0.392573,0.197859,1.000000,0.140647,0.036242,0.292695
DiabetesPedigreeFunction,-0.033523,0.137337,0.041265,0.183928,0.185071,0.140647,1.000000,0.033561,0.173844
Age,0.544341,0.263514,0.239528,-0.113970,-0.042163,0.036242,0.033561,1.000000,0.238356
Outcome,0.221898,0.466581,0.065068,0.074752,0.130548,0.292695,0.173844,0.238356,1.000000

In [9]:
Response_PredVars = data[['Pregnancies','Glucose','BMI', 'Age','Outcome']]
Response_PredVars.corr()

             Pregnancies   Glucose       BMI       Age   Outcome
Pregnancies     1.000000  0.129459  0.017683  0.544341  0.221898
Glucose         0.129459  1.000000  0.221071  0.263514  0.466581
BMI             0.017683  0.221071  1.000000  0.036242  0.292695
Age             0.544341  0.263514  0.036242  1.000000  0.238356
Outcome         0.221898  0.466581  0.292695  0.238356  1.000000

In [10]:
X = data[['Pregnancies','Glucose','BMI','Age',]]
Y = data['Outcome']
X,Y

(     Pregnancies  Glucose   BMI  Age
 0              6      148  33.6   50
 1              1       85  26.6   31
 2              8      183  23.3   32
 3              1       89  28.1   21
 4              0      137  43.1   33
 ..           ...      ...   ...  ...
 763           10      101  32.9   63
 764            2      122  36.8   27
 765            5      121  26.2   30
 766            1      126  30.1   47
 767            1       93  30.4   23

 [768 rows x 4 columns],
 0      1
 1      0
 2      1
 3      0
 4      1
       ..
 763    0
 764    0
 765    0
 766    1
 767    0
 Name: Outcome, Length: 768, dtype: int64)

In [11]:
x_train, x_test, y_train, y_test = train_test_split(X,Y,random_state=0,test_size=0.33)
print(x_train.shape, y_train.shape,x_test.shape,y_test.shape)

(514, 4) (514,) (254, 4) (254,)

In [12]:
from sklearn import linear_model
linreg = linear_model.LinearRegression()
linreg.fit(x_train, y_train)

LinearRegression()

In [14]:
import statsmodels.formula.api as smf
trainDataExcel = pd.concat([x_train, y_train], axis=1)
testDataExcel = pd.concat([x_test, y_test], axis=1)
mlr = smf.ols(formula='Outcome ~ Pregnancies + Glucose + BMI + Age', data=trainDataExcel).fit()
print(mlr.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                Outcome   R-squared:                       0.286
Model:                            OLS   Adj. R-squared:                  0.281
Method:                 Least Squares   F-statistic:                     51.08
Date:                Mon, 07 Apr 2025   Prob (F-statistic):           3.70e-36
Time:                        07:56:14   Log-Likelihood:                -264.71
No. Observations:                 514   AIC:                             539.4
Df Residuals:                     509   BIC:                             560.6
Df Model:                           4
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept      -0.9070      0.098     -9.290      0.000      -1.099      -0.715
Pregnancies     0.0160      0.006      2.552      0.011       0.004       0.028
Glucose         0.0056      0.001      9.327      0.000       0.004       0.007
BMI             0.0128      0.002      5.577      0.000       0.008       0.017
Age             0.0034      0.002      1.814      0.070      -0.000       0.007
==============================================================================
Omnibus:                       37.765   Durbin-Watson:                   1.949
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               22.908
Skew:                           0.377   Prob(JB):                     1.06e-05
Kurtosis:                       2.292   Cond. No.                         730.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [15]:
mlr = smf.ols(formula='Outcome ~ Pregnancies + Glucose + BMI + Age', data=testDataExcel).fit()
print(mlr.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                Outcome   R-squared:                       0.285
Model:                            OLS   Adj. R-squared:                  0.274
Method:                 Least Squares   F-statistic:                     24.81
Date:                Mon, 07 Apr 2025   Prob (F-statistic):           2.64e-17
Time:                        07:56:20   Log-Likelihood:                -126.28
No. Observations:                 254   AIC:                             262.6
Df Residuals:                     249   BIC:                             280.2
Df Model:                           4
Covariance Type:            nonrobust
===============================================================================
                  coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------
Intercept      -0.8583      0.144     -5.964      0.000      -1.142      -0.575
Pregnancies     0.0280      0.009      3.052      0.003       0.010       0.046
Glucose         0.0063      0.001      7.384      0.000       0.005       0.008
BMI             0.0110      0.003      3.195      0.002       0.004       0.018
Age            -0.0004      0.003     -0.142      0.887      -0.006       0.005
==============================================================================
Omnibus:                       15.397   Durbin-Watson:                   1.797
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               11.352
Skew:                           0.408   Prob(JB):                      0.00343
Kurtosis:                       2.361   Cond. No.                         750.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.